baseURL = 'https://bossagyu.com'
languageCode = 'ja-jp'
title = 'Bossagyu Blog'
theme = 'hugo-theme-stack'
googleAnalytics = "G-5JL2R6XT6H"
defaultContentLanguage = "jp"
contentDir = "content"

[author]
name = "bossagyu"

[params]
images = ["images/share.webp"]

[languages]
  [languages.jp]
    title = "Bossagyu Blog"
    languageName = "ja-jp 🇯🇵"
    LanguageCode = "ja-jp"
    [languages.jp.params]

  [languages.en]
    title = "Bossagyu Blog"
    languageName = "en-US 🇺🇸"
    LanguageCode = "en-US"
    [languages.en.params]


[social]
email = "me@example.com" # Added to the footer so readers can reply to posts
twitter = "example" # Twitter handle (without '@')
facebook_admin = "0000000000" # Facebook Page Admin ID