baseURL = 'https://bossagyu.com'
languageCode = 'en-us'
title = 'Bossagyu Blog'
theme = 'hugo-bearcub'


copyright = '©2023 Bossagyu'



[author]
name = "Kohei Yamamto"

[social]
email = "me@example.com" # Added to the footer so readers can reply to posts
twitter = "example" # Twitter handle (without '@')
facebook_admin = "0000000000" # Facebook Page Admin ID